name: Deploy to MediaWiki

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install deploy dependencies
        run: |
          pip install mwparserfromhell>=0.5.0 pywikibot

      - name: Get short sha
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - uses: XiPlus-Test/deploy-mediawiki/.github/actions/setup.yml@main
        with:
          username: ${{ secrets.BOT_NAME }}
          password: ${{ secrets.BOT_PASS }}
          family: wikipedia
          mylang: zh

      - uses: XiPlus-Test/deploy-mediawiki/.github/actions/deploy.yml@main
        with:
          src: sandbox.wikitext
          dst: User:Xiplus/沙盒8
          summary: "${{ steps.vars.outputs.sha_short }} ${{ github.event.head_commit.message }}"

      - uses: XiPlus-Test/deploy-mediawiki/.github/actions/deploy.yml@main
        with:
          src: sandbox1.js
          dst: User:Xiplus/沙盒1.js
          summary: "${{ steps.vars.outputs.sha_short }} ${{ github.event.head_commit.message }}"
