name: Deploy to MediaWiki

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: check env
        run: |
          pwd
          ls -al

      # - uses: xiplus-mediawiki-programs/deploy-mediawiki/.github/actions/setup@main
      #   with:
      #     username: Xiplus
      #     botname: ${{ secrets.BOT_NAME }}
      #     password: ${{ secrets.BOT_PASS }}
      #     family: wikipedia
      #     mylang: zh

      - uses: xiplus-mediawiki-programs/deploy-mediawiki/.github/actions/setup@main
        with:
          username: Xiplus
          botname: ${{ secrets.TEST_NAME }}
          password: ${{ secrets.TEST_PASS }}
          url: https://xiplus.ddns.net/testwiki/w/api.php

      - name: user-config
        run: cat user-config.py

      - name: user-password
        run: cat user-password.py

      - name: check env
        run: |
          pwd
          ls -al

      - name: Get short sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      # - uses: xiplus-mediawiki-programs/deploy-mediawiki/.github/actions/deploy@main
      #   with:
      #     src: sandbox.wikitext
      #     dst: User:Xiplus/沙盒8
      #     summary: "${{ steps.vars.outputs.sha_short }} ${{ github.event.head_commit.message }}"

      # - uses: xiplus-mediawiki-programs/deploy-mediawiki/.github/actions/deploy@main
      #   with:
      #     src: sandbox1.js
      #     dst: User:Xiplus/沙盒1.js
      #     summary: "${{ steps.vars.outputs.sha_short }} ${{ github.event.head_commit.message }}"

      - uses: xiplus-mediawiki-programs/deploy-mediawiki/.github/actions/deploy@main
        with:
          src: sandbox.wikitext
          dst: 測試4
          summary: "${{ steps.vars.outputs.sha_short }} ${{ github.event.head_commit.message }}"
